// ZanPlayer Lite release automation (SemVer pipeline)
//
// Usage (from project root):
//   npm run release -- patch          # 0.1.1 -> 0.1.2  (bug fixes)
//   npm run release -- minor          # 0.1.1 -> 0.2.0  (new features)
//   npm run release -- major          # 0.1.1 -> 1.0.0  (breaking changes)
//   npm run release -- 0.1.2          # explicit version
//   npm run release -- patch --dry-run  # preview changes, no writes or git ops
//
// Flow:
//   1. Loads the current version from package.json.
//   2. Verifies it matches src-tauri/Cargo.toml, src-tauri/tauri.conf.json,
//      src-tauri/Cargo.lock and package-lock.json (all five must be in sync).
//   3. Verifies the working tree is clean.
//   4. Bumps the version in all five files.
//   5. Commits "chore: release vX.Y.Z", tags vX.Y.Z, pushes main and the tag
//      (the tag triggers the GitHub Actions release workflow).

import { readFileSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const SEMVER_RE = /^\d+\.\d+\.\d+$/;
const INC_KINDS = ["patch", "minor", "major"];

const read = (rel) => readFileSync(join(ROOT, rel), "utf8");
const write = (rel, text) => writeFileSync(join(ROOT, rel), text, "utf8");

// ---------------------------------------------------------------------------
// Version readers / writers
// ---------------------------------------------------------------------------

const readPackageJson = (text) => JSON.parse(text).version;

const setPackageJson = (text, version) =>
  text.replace(/"version"\s*:\s*"[^"]+"/, `"version": "${version}"`);

const readTauriConfigJson = (text) => text.match(/"version"\s*:\s*"([^"]+)"/)?.[1] ?? null;

const setTauriConfigJson = (text, version) =>
  text.replace(/"version"\s*:\s*"[^"]+"/, `"version": "${version}"`);

// Cargo.toml: only the `version` key directly under [package]
const readCargoToml = (text) =>
  text.match(/\[package\][\s\S]*?^version\s*=\s*"([^"]+)"/m)?.[1] ?? null;

const setCargoToml = (text, version) =>
  text.replace(/(\[package\][\s\S]*?^version\s*=\s*)"[^"]+"/m, `$1"${version}"`);

// Cargo.lock: only the [[package]] block whose name is the app crate
const readCargoLock = (text) =>
  text.match(/\[\[package\]\]\nname = "zanplayer-lite"\nversion\s*=\s*"([^"]+)"/)?.[1] ?? null;

const setCargoLock = (text, version) =>
  text.replace(
    /(\[\[package\]\]\nname = "zanplayer-lite"\nversion\s*=\s*)"[^"]+"/,
    `$1"${version}"`
  );

// package-lock.json: root version + the "" / node_modules entries (generated by npm)
const readPackageLock = (text) => {
  const obj = JSON.parse(text);
  return obj.packages?.[""]?.version ?? obj.version;
};

const setPackageLock = (text, version) => {
  const obj = JSON.parse(text);
  obj.version = version;
  if (obj.packages?.[""]) obj.packages[""].version = version;
  if (obj.packages?.["node_modules/zanplayer-lite"]) obj.packages["node_modules/zanplayer-lite"].version = version;
  return `${JSON.stringify(obj, null, 2)}\n`;
};

const FILES = [
  { path: "package.json", read: readPackageJson, set: setPackageJson },
  { path: "src-tauri/Cargo.toml", read: readCargoToml, set: setCargoToml },
  { path: "src-tauri/Cargo.lock", read: readCargoLock, set: setCargoLock },
  { path: "src-tauri/tauri.conf.json", read: readTauriConfigJson, set: setTauriConfigJson },
  { path: "package-lock.json", read: readPackageLock, set: setPackageLock },
];

// ---------------------------------------------------------------------------
// SemVer helpers
// ---------------------------------------------------------------------------

function nextVersion(current, arg) {
  if (SEMVER_RE.test(arg)) return arg;
  if (!INC_KINDS.includes(arg)) return null;
  const [maj, min, pat] = current.split(".").map(Number);
  if (arg === "major") return `${maj + 1}.0.0`;
  if (arg === "minor") return `${maj}.${min + 1}.0`;
  return `${maj}.${min}.${pat + 1}`;
}

function run(cmd, args) {
  const res = spawnSync(cmd, args, { cwd: ROOT, stdio: "inherit" });
  if (res.status !== 0) {
    console.error(`\nFailed: ${cmd} ${args.join(" ")} (exit ${res.status ?? res.error?.message ?? "unknown"})`);
    process.exit(res.status ?? 1);
  }
}

function fail(message) {
  console.error(message);
  process.exit(1);
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

const args = process.argv.slice(2);
const dryRun = args.includes("--dry-run");
const bumpArg = args.find((a) => a !== "--dry-run");

if (!bumpArg) {
  fail(`Usage: npm run release -- <patch|minor|major|x.y.z> [--dry-run]\n\nCurrent version: ${FILES[0].read(read(FILES[0].path))}`);
}

const current = readPackageJson(read("package.json"));
const versions = Object.fromEntries(FILES.map((f) => [f.path, f.read(read(f.path))]));
const outOfSync = FILES.filter((f) => versions[f.path] !== current);
if (outOfSync.length > 0) {
  fail(
    `Version mismatch — release requires EXACT sync across all sources.\n` +
      outOfSync.map((f) => `  ${f.path}: ${versions[f.path]} (expected ${current})`).join("\n") +
      `\nFix these before releasing (e.g. npm run release -- ${current} won't help — sync manually first).`
  );
}

if (!dryRun) {
  const dirty = spawnSync("git", ["status", "--porcelain"], { cwd: ROOT, encoding: "utf8" }).stdout.trim();
  if (dirty) {
    fail(`Working tree is not clean:\n${dirty}\nCommit or stash changes before releasing.`);
  }
}

const next = nextVersion(current, bumpArg);
if (!next) {
  fail(`Invalid version "${bumpArg}". Use patch, minor, major, or an explicit semver like "0.1.2".`);
}
if (next === current) {
  fail(`Version is already ${current}; nothing to release.`);
}

if (dryRun) {
  console.log(`[dry-run] ${current} -> ${next}`);
  for (const f of FILES) {
    const updated = f.set(read(f.path), next);
    const ok = f.read(updated) === next;
    console.log(`[dry-run] ${ok ? "OK  " : "FAIL"} ${f.path} -> ${next}`);
  }
  console.log("[dry-run] commit:   chore: release v" + next);
  console.log("[dry-run] tag:      v" + next);
  console.log("[dry-run] push:     origin main, origin v" + next);
  process.exit(0);
}

console.log(`Bumping ${current} -> ${next}...`);
for (const f of FILES) {
  const updated = f.set(read(f.path), next);
  if (f.read(updated) !== next) {
    fail(`Failed to write ${f.path}; aborting before any git operations.`);
  }
  write(f.path, updated);
}
console.log("Version synced across:", FILES.map((f) => f.path).join(", "));

run("git", ["add", "."]);
run("git", ["commit", "-m", `chore: release v${next}`]);
run("git", ["tag", `v${next}`]);
run("git", ["push", "origin", "main"]);
run("git", ["push", "origin", `v${next}`]);

console.log(`\nReleased v${next} — tag push triggers the GitHub Actions release workflow.`);